//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ContainerID { get; set; }
        public string ContainerName { get; set; }
        public string ContainerHeight { get; set; }
        public string ContainerWidth { get; set; }
        public string ContainerLength { get; set; }
        public string ContainerWeight { get; set; }
    }
}
